# permissions for end users to edit routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: route-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: routes-operator
    app.kubernetes.io/part-of: routes-operator
    app.kubernetes.io/managed-by: kustomize
  name: route-editor-role
rules:
- apiGroups:
  - networking.verrazzano.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.verrazzano.io
  resources:
  - routes/status
  verbs:
  - get
